name: dart_crs
description: This package extends proj4dart by embedding the EPSG
  Geodetic Parameter Dataset maintained by the Geodesy Subcommittee of the
  IOGP Geomatics Committee.
version: 1.0.1
repository: https://github.com/badger3512/dart_pcs

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  proj4dart: ^2.1.0
  path: ^1.8.3
  sqflite: ^2.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
flutter:
  uses-material-design: true
  assets:
    - packages/dart_crs/assets/epsg.db